### ISSUE TITLE
Updatable `regexpPatterns`

### ISSUE THREAD

**Issue by seitbekir** [seitbekir/project-lint#2]
In the code now there is a presets like `${{PascalCase}}`, etc...

Need to create a param for custom checks, that might be used the same way.

Example

```yaml
regexpPatterns:
  MyOwnCheck: [0-9]\.[a-z]

root:
  - name: /^${{MyOwnCheck}}\.ams$/
    type: file
```
