### ISSUE TITLE
Default `extends`

### ISSUE THREAD

**Issue by seitbekir** [seitbekir/project-lint#3]
Now there is a folder with the possible extends: `node.yml`

Make this available not by a path, but by a name.

Now:

```yaml
extends: ./node_modules/@seitbekir/project-lint/extends/node.yml

# or

extends:
  - ./node_modules/@seitbekir/project-lint/extends/node.yml
```

Expected:

```yaml
extends: node

# or

extends:
  - node
```

Or better solution?
