### ISSUE TITLE
URL based `extends`

### ISSUE THREAD

**Issue by seitbekir** [seitbekir/project-lint#4]
Make it possible to extend rules not only by path, but also via URL.

It must support cache, and cache clean up.

Now:

```yaml
extends: ../configs-repo/project-lint/rules.yml

# or

extends:
  - ../configs-repo/project-lint/rules.yml
```

Expected:

```yaml
extends: https://configs.local/project-lint/rules.yml

# or

extends:
  - https://configs.local/project-lint/rules.yml
```
